# Generated by Django 4.1.7 on 2023-03-02 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('1', 'Face Cream'), ('2', 'Hands Cream'), ('3', 'Body Cream')], default='1', max_length=50),
        ),
    ]
