# Generated by Django 4.1.7 on 2023-03-02 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Face Cream', '1'), ('Hands Cream', '2'), ('Body Cream', '3')], default='1', max_length=50),
        ),
    ]
